const fs = require('fs');  
const c = fs.readFileSync('src/components/common/Modals/__tests__/MandatoryBreakModal.test.jsx','utf8');  
const lines = c.split('\n');  
lines[231] = \"    it('contains note about manual resume requirement', async () => {\";  
lines[232] = \"      render(^<MandatoryBreakModal {...defaultProps} breakTimeRemaining={1} /^>);\";  
lines[233] = \"\";  
lines[234] = \"      vi.advanceTimersByTime(1000);\";  
lines[235] = \"\";  
lines[236] = \"      await waitFor(() => {\";  
lines[237] = \"        expect(\";  
lines[238] = \"          screen.getByText(/You must manually click to resume/i)\";  
lines[239] = \"        ).toBeInTheDocument();\";  
lines[240] = \"      });\";  
lines[241] = \"    });\";  
fs.writeFileSync('src/components/common/Modals/__tests__/MandatoryBreakModal.test.jsx', lines.join('\n'),'utf8');  
console.log('Done');  
